# Generated by Django 5.0.1 on 2024-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_atividade_status_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='projeto_principal',
            field=models.BooleanField(default=False, verbose_name='Projeto Principal'),
        ),
    ]
