# Generated by Django 5.0.2 on 2024-02-20 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_projeto_motivo_cancelamento_motivocancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivocancelamento',
            name='data_cancelamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
